In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.metrics import confusion_matrix

In [2]:
iris = load_iris()
X = iris.data
y = iris.target

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [4]:
# Multinomial Naive Bayes classifier
multinomial_nb = MultinomialNB()
multinomial_nb.fit(X_train, y_train)
y_pred_multinomial = multinomial_nb.predict(X_test)

In [5]:
# Bernoulli Naive Bayes classifier
bernoulli_nb = BernoulliNB()
bernoulli_nb.fit(X_train, y_train)
y_pred_bernoulli = bernoulli_nb.predict(X_test)

In [6]:
# Confusion matrix for Multinomial Naive Bayes
confusion_matrix_multinomial = confusion_matrix(y_test, y_pred_multinomial)
print("Confusion Matrix (Multinomial Naive Bayes):\n", confusion_matrix_multinomial)

Confusion Matrix (Multinomial Naive Bayes):
 [[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]


In [7]:
# Confusion matrix for Bernoulli Naive Bayes
confusion_matrix_bernoulli = confusion_matrix(y_test, y_pred_bernoulli)
print("Confusion Matrix (Bernoulli Naive Bayes):\n", confusion_matrix_bernoulli)

Confusion Matrix (Bernoulli Naive Bayes):
 [[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]


In [8]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.metrics import confusion_matrix
import numpy as np

# Load the dataset (Iris dataset used as an example)
iris = load_iris()
X = iris.data
y = iris.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Multinomial Naive Bayes classifier
multinomial_nb = MultinomialNB()
multinomial_nb.fit(X_train, y_train)
y_pred_multinomial = multinomial_nb.predict(X_test)

# Bernoulli Naive Bayes classifier
bernoulli_nb = BernoulliNB()
bernoulli_nb.fit(X_train, y_train)
y_pred_bernoulli = bernoulli_nb.predict(X_test)

# Confusion matrix for Multinomial Naive Bayes
confusion_matrix_multinomial = confusion_matrix(y_test, y_pred_multinomial)
converted_matrix_multinomial = confusion_matrix_multinomial[:2, :2]

# Confusion matrix for Bernoulli Naive Bayes
confusion_matrix_bernoulli = confusion_matrix(y_test, y_pred_bernoulli)
converted_matrix_bernoulli = confusion_matrix_bernoulli[:2, :2]

print("Converted Confusion Matrix (Multinomial Naive Bayes):")
print(converted_matrix_multinomial)
print()
print("Converted Confusion Matrix (Bernoulli Naive Bayes):")
print(converted_matrix_bernoulli)


Converted Confusion Matrix (Multinomial Naive Bayes):
[[10  0]
 [ 0  9]]

Converted Confusion Matrix (Bernoulli Naive Bayes):
[[ 0 10]
 [ 0  9]]


# confusion matrix
(1). The first row and first column correspond to the true positives (correct predictions).

(2).The first row and second column correspond to the false negatives (instances where the true label is positive but the classifier predicted it as negative).
(3).The second row and first column correspond to the false positives (instances where the true label is negative but the classifier predicted it as positive).

(4). The second row and second column correspond to the true negatives (correctly predicted negative instances).